// <auto-generated />
using System;
using BioApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BioApp.Migrations
{
    [DbContext(typeof(BioContext))]
    [Migration("20231216183312_patient_visit_0_1_5")]
    partial class patient_visit_0_1_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BioApp.Models.Analysis", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisIsPerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfAnalysis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBiosampleCollecting")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MelanomaTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("bioSample")
                        .HasColumnType("int");

                    b.Property<bool>("earlyMetastasis")
                        .HasColumnType("bit");

                    b.Property<bool>("lateMetastasis")
                        .HasColumnType("bit");

                    b.Property<bool>("melanomaConfirmedEarlyStage")
                        .HasColumnType("bit");

                    b.Property<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("preventiveCare")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MelanomaTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Analysis");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarker", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("analysisType")
                        .HasColumnType("int");

                    b.Property<int>("dataType")
                        .HasColumnType("int");

                    b.Property<string>("measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("measureEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderRank")
                        .HasColumnType("int");

                    b.Property<double>("probability")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("AnalysisMarker");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarkerData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisMarkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommonAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("boolValue")
                        .HasColumnType("bit");

                    b.Property<double?>("doubleValue")
                        .HasColumnType("float");

                    b.Property<string>("stringValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AnalysisMarkerId");

                    b.HasIndex("CommonAnalysisId");

                    b.ToTable("AnalysisMarkerData");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarkerNormValue", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisMarkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("maxValue")
                        .HasColumnType("float");

                    b.Property<double>("minValue")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("AnalysisMarkerId");

                    b.HasIndex("PatientGroupId");

                    b.ToTable("AnalysisMarkerNormValue");
                });

            modelBuilder.Entity("BioApp.Models.BioFile", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BioFileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientVisitsid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("BioFileTypeId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientVisitsid");

                    b.ToTable("BioFile");
                });

            modelBuilder.Entity("BioApp.Models.BioFileType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BioFileType");
                });

            modelBuilder.Entity("BioApp.Models.CommonAnalysis", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisIsPerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfAnalysis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBiosampleCollecting")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("analysisType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("CommonAnalysis");
                });

            modelBuilder.Entity("BioApp.Models.Doctor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorSpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DoctorSpecializationId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("BioApp.Models.DoctorSpecialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DoctorSpecialization");
                });

            modelBuilder.Entity("BioApp.Models.KITMarker", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NA")
                        .HasColumnType("bit");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("absent")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("heterozygosity")
                        .HasColumnType("bit");

                    b.Property<bool>("homozygosity")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("TypeId");

                    b.ToTable("KITMarkers");
                });

            modelBuilder.Entity("BioApp.Models.KITType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("KITTypes");
                });

            modelBuilder.Entity("BioApp.Models.MKBClassifier", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<Guid?>("PatientVisitsid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("additionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nodeCount")
                        .HasColumnType("int");

                    b.Property<string>("parentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientVisitsid");

                    b.HasIndex("parentId");

                    b.ToTable("MKBClassifier");
                });

            modelBuilder.Entity("BioApp.Models.MelanomaType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameLat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MelanomaType");
                });

            modelBuilder.Entity("BioApp.Models.Patient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("HormonalChanges")
                        .HasColumnType("bit");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OMSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObligateFormsOfPrecancer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PatientVisitsid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PresenceOfFreckles")
                        .HasColumnType("bit");

                    b.Property<string>("SNILS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("XerodermaPigmentosum")
                        .HasColumnType("bit");

                    b.Property<int>("ageGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("birthmarks")
                        .HasColumnType("int");

                    b.Property<int>("burns")
                        .HasColumnType("int");

                    b.Property<int>("compoundMelonoma")
                        .HasColumnType("int");

                    b.Property<DateTime>("datePassport")
                        .HasColumnType("datetime2");

                    b.Property<int>("eyeType")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<int>("geneticAbnormalitiesInChromosomes")
                        .HasColumnType("int");

                    b.Property<int>("hairType")
                        .HasColumnType("int");

                    b.Property<int>("hormonalChangesNew")
                        .HasColumnType("int");

                    b.Property<bool>("immuneSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("immuneSystemDiseases")
                        .HasColumnType("bit");

                    b.Property<string>("issuedByPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("melanoma")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nevus")
                        .HasColumnType("int");

                    b.Property<int>("nevusType")
                        .HasColumnType("int");

                    b.Property<bool>("numberOfMoles")
                        .HasColumnType("bit");

                    b.Property<string>("numberPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parents")
                        .HasColumnType("int");

                    b.Property<string>("passportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("previousMelanoma")
                        .HasColumnType("bit");

                    b.Property<bool>("previousMelanomaInFamily")
                        .HasColumnType("bit");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("relatives")
                        .HasColumnType("int");

                    b.Property<string>("seriaPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("simba")
                        .HasColumnType("int");

                    b.Property<int>("skinType")
                        .HasColumnType("int");

                    b.Property<int>("uf")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PatientVisitsid");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("BioApp.Models.PatientGroup", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("PatientGroup");
                });

            modelBuilder.Entity("BioApp.Models.PatientVisits", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("HormonalChanges")
                        .HasColumnType("bit");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OMSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObligateFormsOfPrecancer")
                        .HasColumnType("bit");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PresenceOfFreckles")
                        .HasColumnType("bit");

                    b.Property<string>("SNILS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("XerodermaPigmentosum")
                        .HasColumnType("bit");

                    b.Property<int>("ageGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("birthmarks")
                        .HasColumnType("int");

                    b.Property<int>("burns")
                        .HasColumnType("int");

                    b.Property<int>("compoundMelonoma")
                        .HasColumnType("int");

                    b.Property<DateTime>("datePassport")
                        .HasColumnType("datetime2");

                    b.Property<int>("eyeType")
                        .HasColumnType("int");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<int>("geneticAbnormalitiesInChromosomes")
                        .HasColumnType("int");

                    b.Property<int>("hairType")
                        .HasColumnType("int");

                    b.Property<int>("hormonalChangesNew")
                        .HasColumnType("int");

                    b.Property<bool>("immuneSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("immuneSystemDiseases")
                        .HasColumnType("bit");

                    b.Property<string>("issuedByPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("melanoma")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nevus")
                        .HasColumnType("int");

                    b.Property<int>("nevusType")
                        .HasColumnType("int");

                    b.Property<bool>("numberOfMoles")
                        .HasColumnType("bit");

                    b.Property<string>("numberPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parents")
                        .HasColumnType("int");

                    b.Property<string>("passportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("previousMelanoma")
                        .HasColumnType("bit");

                    b.Property<bool>("previousMelanomaInFamily")
                        .HasColumnType("bit");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("relatives")
                        .HasColumnType("int");

                    b.Property<string>("seriaPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("simba")
                        .HasColumnType("int");

                    b.Property<int>("skinType")
                        .HasColumnType("int");

                    b.Property<int>("uf")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("PatientVisits");
                });

            modelBuilder.Entity("MKBClassifierPatient", b =>
                {
                    b.Property<int>("MKBClassifiersid")
                        .HasColumnType("int");

                    b.Property<Guid>("Patientsid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MKBClassifiersid", "Patientsid");

                    b.HasIndex("Patientsid");

                    b.ToTable("MKBClassifierPatient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BioApp.Models.Analysis", b =>
                {
                    b.HasOne("BioApp.Models.Doctor", "doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.MelanomaType", "melanomaType")
                        .WithMany()
                        .HasForeignKey("MelanomaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("melanomaType");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarkerData", b =>
                {
                    b.HasOne("BioApp.Models.AnalysisMarker", "analysisMarker")
                        .WithMany()
                        .HasForeignKey("AnalysisMarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.CommonAnalysis", "commonAnalysis")
                        .WithMany()
                        .HasForeignKey("CommonAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("analysisMarker");

                    b.Navigation("commonAnalysis");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarkerNormValue", b =>
                {
                    b.HasOne("BioApp.Models.AnalysisMarker", "AnalysisMarker")
                        .WithMany("analysisMarkerNormValues")
                        .HasForeignKey("AnalysisMarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.PatientGroup", "PatientGroup")
                        .WithMany()
                        .HasForeignKey("PatientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisMarker");

                    b.Navigation("PatientGroup");
                });

            modelBuilder.Entity("BioApp.Models.BioFile", b =>
                {
                    b.HasOne("BioApp.Models.BioFileType", "fileType")
                        .WithMany("files")
                        .HasForeignKey("BioFileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.Patient", "patient")
                        .WithMany("files")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.PatientVisits", null)
                        .WithMany("files")
                        .HasForeignKey("PatientVisitsid");

                    b.Navigation("fileType");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("BioApp.Models.CommonAnalysis", b =>
                {
                    b.HasOne("BioApp.Models.Doctor", "doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("BioApp.Models.Doctor", b =>
                {
                    b.HasOne("BioApp.Models.DoctorSpecialization", "doctorSpecialization")
                        .WithMany("docs")
                        .HasForeignKey("DoctorSpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctorSpecialization");
                });

            modelBuilder.Entity("BioApp.Models.KITMarker", b =>
                {
                    b.HasOne("BioApp.Models.Analysis", "analysis")
                        .WithMany("kitMarkers")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.KITType", "type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("analysis");

                    b.Navigation("type");
                });

            modelBuilder.Entity("BioApp.Models.MKBClassifier", b =>
                {
                    b.HasOne("BioApp.Models.PatientVisits", null)
                        .WithMany("MKBClassifiers")
                        .HasForeignKey("PatientVisitsid");

                    b.HasOne("BioApp.Models.MKBClassifier", "parent")
                        .WithMany()
                        .HasForeignKey("parentId");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("BioApp.Models.Patient", b =>
                {
                    b.HasOne("BioApp.Models.PatientVisits", null)
                        .WithMany("Patients")
                        .HasForeignKey("PatientVisitsid");
                });

            modelBuilder.Entity("MKBClassifierPatient", b =>
                {
                    b.HasOne("BioApp.Models.MKBClassifier", null)
                        .WithMany()
                        .HasForeignKey("MKBClassifiersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioApp.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("Patientsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BioApp.Models.Analysis", b =>
                {
                    b.Navigation("kitMarkers");
                });

            modelBuilder.Entity("BioApp.Models.AnalysisMarker", b =>
                {
                    b.Navigation("analysisMarkerNormValues");
                });

            modelBuilder.Entity("BioApp.Models.BioFileType", b =>
                {
                    b.Navigation("files");
                });

            modelBuilder.Entity("BioApp.Models.DoctorSpecialization", b =>
                {
                    b.Navigation("docs");
                });

            modelBuilder.Entity("BioApp.Models.Patient", b =>
                {
                    b.Navigation("files");
                });

            modelBuilder.Entity("BioApp.Models.PatientVisits", b =>
                {
                    b.Navigation("files");

                    b.Navigation("MKBClassifiers");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
